Feature/cadastrar material
GustavoPrim/Entra21-TrabalhoFinal-FoxBudgets pull request #52
Opened 2022-09-10 01:08 UTC by GuilhermeDMueller

Criado MaterialRepositorio e IMaterialRepositorio;
Criado Enum Material;
Adicionado Material ao OrcamentoContexto;
Material recebe herança de EntidadeBase.

2022-09-12 21:42 UTC, GustavoPrim requested changes

2022-09-12 21:42 UTC, GustavoPrim commented on Repositorio/Repositorios/IMaterialRepositorio.cs
> +        public Material Cadastrar(Material material);
não usar o public na interface

2022-09-12 21:42 UTC, GustavoPrim commented on Servico/Extensions/ClienteExtension.cs
> +﻿namespace Servico.Extensions
já foi feito o ClienteExtensions

2022-09-12 21:42 UTC, GustavoPrim commented on Repositorio/Enuns/ClienteGenero.cs
> +﻿namespace Repositorio.Enuns
foi mudado na uml do projeto, não vai ser usado o Genero

2022-09-14 21:24 UTC, GustavoPrim approved these changes

2022-09-14 22:38 UTC, LucasPerezAlves approved these changes

2022-09-14 22:38 UTC, merged