Feature/cadastrar cliente
GustavoPrim/Entra21-TrabalhoFinal-FoxBudgets pull request #9
Opened 2022-09-01 00:38 UTC by GuilhermeDMueller

2022-09-01 00:40 UTC, LucasPerezAlves reviewed
Colocar específicação detalhada do projeto no commit e não fazer somente um push

2022-09-01 00:40 UTC, GustavoPrim reviewed
Colocar informações detalhadas do seu projeto

2022-09-01 00:41 UTC, Willljdev approved these changes

2022-09-01 01:11 UTC, Willljdev reviewed
Nome e NomeConstrutora, não precisa, pois se for pessoa Física terá o campo para por cpf, se for pessoa jurídica terá CNPJ, então o campo nome será apenas um, oque via distinguir se uma pessoa comum ou uma construtora, será a opção escolhida entre CPF ou CNPJ.

Isso vale para os outros pontos em duplicidade

2022-09-04 15:38 UTC, LucasPerezAlves requested changes

2022-09-04 15:38 UTC, LucasPerezAlves commented on Repositorio/Migrations/ClienteContextoModelSnapshot.cs
> +
Retirar linhas em branco

2022-09-04 18:10 UTC, GuilhermeDMueller commented
Últimos 3 Commits.

2022-09-05 21:22 UTC, GustavoPrim approved these changes

2022-09-05 21:22 UTC, GustavoPrim commented on Aplicacao.Cliente/Pages/Index.cshtml
> +    <p>Faça o seu Cadastramanento de Cliente ou Construtora</p>
corrigir aqui o erro na frase

2022-09-05 21:22 UTC, GustavoPrim commented on Repositorio/BancoDados/ClienteContexto.cs
> +            /*
não precisa colocar esses comentários no trabalho, tem no exemplo pra ser usado corretamente no trabalho

2022-09-05 21:22 UTC, GustavoPrim commented on Repositorio/Mapeamentos/ClienteMapeamento.cs
> +            /*builder.HasKey(x => x.Id).HasName("id");
não precisa ser exatamente igual ao exemplo, só precisamos usar o necessário

2022-09-05 23:10 UTC, LucasPerezAlves approved these changes

2022-09-05 23:10 UTC, LucasPerezAlves commented on Repositorio/BancoDados/ClienteContexto.cs
> +            * 3ª etapa - Registrar o mapeamento no próprio Contexto
Tirar os comentários

2022-09-05 23:11 UTC, merged